<?php

use yii\db\Migration;

class m190627_120647_add_flightcentre extends Migration
{
    public function safeUp()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }

        $this->execute('INSERT INTO quote_company SET id=9, image="flight_centre.png", company_name="Flight Centre", method_name="createQuoteFlightCentre", info="Hotels, experiences, car hire, insurance, visa, not to mention finding the right flight... We get it. Planning a holiday can be hard. But that`s where Flight Centre can help. Whether it`s a city break, beach holiday, or dreamy big adventure (to name a few!), we`ll take the hassle out of the organisation, so you can focus on having an amazing time. And it`s our lovely Travel Consultants we have to thank. Pop in-store or give us a bell, and they`ll get to know you, your travel style and your budget to build a unique holiday. They`ll source the best deals and have your back before, during and after your trip. It`s no surprise, then, that we have more 5-star reviews than any other travel agent! Let our friendly people tailor-make it easy."');


        $this->createTable('{{%quote_company_destination}}', [
            'id' => $this->primaryKey(),
            'quote_company_id' => $this->integer()->notNull(),
            'destination_value' => $this->string(100)->notNull(),
            'geo_country' => $this->string(100),
            'geo_country_code' => $this->string(2),
            'geo_city' => $this->string(50),
            'geo_region' => $this->string(100),
        ], $tableOptions);

        $this->createIndex('idx_quote_company_id', 'quote_company_destination', 'quote_company_id');
        $this->addForeignKey('fk_quote_company_destination2quote_company', 'quote_company_category', 'quote_company_id', 'quote_company', 'id', 'CASCADE', 'CASCADE');
        $this->createIndex('idx_geo_country', 'quote_company_destination', 'geo_country');
        $this->createIndex('idx_geo_city', 'quote_company_destination', 'geo_city');
        $this->createIndex('idx_geo_region', 'quote_company_destination', 'geo_region');

        $this->batchInsert('quote_company_category',
            ['quote_company_id', 'enquiry_category_id'],
            [
                [9,2],
                [9,3],
            ]
        );

        $this->batchInsert('quote_company_destination',
            ['id', 'quote_company_id', 'destination_value', 'geo_country', 'geo_country_code', 'geo_city', 'geo_region'],
            [
                [1, 9, 'Abu_Dhabi,Middle_East,United_Arab_Emirates', 'United Arab Emirates', 'AE', 'Abu Dhabi', 'Abu Dhabi'],
                [2, 9, 'Adelaide,South_Australia,Australia,Australasia', 'Australia', 'AU', 'Adelaide', ''],
                [3, 9, 'Agra,India,Southeast_Asia,Asia', 'India', 'IN', 'Agra', ''],
                [4, 9, 'Airlie_Beach,Queensland,Australia,Australasia', 'Australia', 'AU', 'Airlie Beach', ''],
                [5, 9, 'Alabama,United_States,North_America', 'United States', 'US', 'Alabama', 'Alabama'],
                [6, 9, 'Alaska,United_States,North_America', 'United States', 'US', 'Alaska', 'Alaska'],
                [7, 9, 'Albany,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Albany', ''],
                [8, 9, 'Alberta,Canada,North_America', 'Canada', 'CA', '', 'Alberta'],
                [9, 9, 'Alice_Springs,Northern_Territory,Australia,Australasia', 'Australia', 'AU', 'Alice Springs', ''],
                [10, 9, 'Alvados,Portugal,Europe', 'Portugal', 'PT', 'Alvados', ''],
                [11, 9, 'Amalfi,Amalfi_Coast,Italy,Europe', 'Italy', 'IT', 'Amalfi', ''],
                [12, 9, 'Amarillo,United_States,North_America', 'United States', 'US', 'Amarillo', ''],
                [13, 9, 'Amboise,France,Europe', 'France', 'FR', 'Amboise', ''],
                [14, 9, 'Amritsar,India,Southeast_Asia,Asia', 'India', 'IN', 'Amritsar', ''],
                [15, 9, 'Amsterdam,Netherlands,Europe', 'Netherlands', 'NL', 'Amsterdam', ''],
                [16, 9, 'Anchorage,Alaska,United_States,North_America', 'United States', 'US', 'Anchorage', ''],
                [17, 9, 'Apollo_Bay,Great_Ocean_Road,Victoria,Australia,Australasia', 'Australia', 'AU', 'Apollo Bay', ''],
                [18, 9, 'Arizona,United_States,North_America', 'United States', 'US', 'Arizona', 'Arizona'],
                [19, 9, 'Arles,France,Europe', 'France', 'FR', 'Arles', ''],
                [20, 9, 'Ashland,Oregon,United_States,North_America', 'United States', 'US', 'Ashland', ''],
                [21, 9, 'Astoria,Oregon,United_States,North_America', 'United States', 'US', 'Astoria', ''],
                [22, 9, 'Auckland,North_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Auckland', 'Auckland'],
                [23, 9, 'Australia,Australasia', 'Australia', 'AU', '', ''],
                [24, 9, 'Austria,Europe', 'Austria', 'AT', '', ''],
                [25, 9, 'Avignon,France,Europe', 'France', 'FR', 'Avignon', ''],
                [26, 9, 'Bahamas,Eastern_Caribbean,Caribbean', 'Bahamas', 'BS', '', ''],
                [27, 9, 'Bali,Indonesia,Southeast_Asia,Asia', 'Indonesia', 'ID', 'Bali', 'Bali'],
                [28, 9, 'Ballarat,Victoria,Australia,Australasia', 'Australia', 'AU', 'Ballarat', ''],
                [29, 9, 'Banff,Alberta,Canada,North_America', 'Canada', 'CA', 'Banff', ''],
                [30, 9, 'Bangkok,Thailand,Southeast_Asia,Asia', 'Thailand', 'TH', 'Bangkok', ''],
                [31, 9, 'Barbados,Southern_Caribbean,Caribbean', 'Barbados', 'BB', '', ''],
                [32, 9, 'Barcelona,Spain,Europe', 'Spain', 'ES', 'Barcelona', ''],
                [33, 9, 'Bar_Harbor,Maine,United_States,North_America', 'United States', 'US', 'Bar Harbor', ''],
                [34, 9, 'Barstow,California,United_States,North_America', 'United States', 'US', 'Barstow', ''],
                [35, 9, 'Batemans_Bay,New_South_Wales,Australia,Australasia', 'Australia', 'AU', 'Batemans Bay', ''],
                [36, 9, 'Beijing,China,Asia', 'China', 'CN', 'Beijing', 'Beijing'],
                [37, 9, 'Bentota,Sri_Lanka,Southeast_Asia,Asia', 'Sri Lanka', 'LK', 'Bentota', ''],
                [38, 9, 'Berlin,Germany,Europe', 'Germany', 'DE', 'Berlin', 'Berlin'],
                [39, 9, 'Bharatpur,India,Southeast_Asia,Asia', 'India', 'IN', 'Bharatpur', ''],
                [40, 9, 'Big_Island,Hawaii,United_States,North_America', 'United States', 'US', 'Big Island', ''],
                [41, 9, 'Bluff,Utah,United_States,North_America', 'United States', 'US', 'Bluff', ''],
                [42, 9, 'Bodega_Bay,California,United_States,North_America', 'United States', 'US', 'Bodega Bay', ''],
                [43, 9, 'Bordeaux,France,Europe', 'France', 'FR', 'Bordeaux', ''],
                [44, 9, 'Boston,Massachusetts,United_States,North_America', 'United States', 'US', 'Boston', ''],
                [45, 9, 'Bowling_Green,United_States,North_America', 'United States', 'US', 'Bowling Green', ''],
                [46, 9, 'Brisbane,Queensland,Australia,Australasia', 'Australia', 'AU', 'Brisbane', ''],
                [47, 9, 'British_Columbia,Canada,North_America', 'Canada', 'CA', '', 'British Columbia'],
                [48, 9, 'Bromo,Indonesia,Southeast_Asia,Asia', 'Indonesia', 'ID', 'Bromo', ''],
                [49, 9, 'Broome,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Broome', ''],
                [50, 9, 'Budapest,Hungary,Europe', 'Hungary', 'HU', 'Budapest', 'Budapest'],
                [51, 9, 'Burgos,Spain,Europe', 'Spain', 'ES', 'Burgos', ''],
                [52, 9, 'Byron_Bay,New_South_Wales,Australia,Australasia', 'Australia', 'AU', 'Byron Bay', ''],
                [53, 9, 'Cairns,Queensland,Australia,Australasia', 'Australia', 'AU', 'Cairns', ''],
                [54, 9, 'Calgary,Alberta,Canada,North_America', 'Canada', 'CA', 'Calgary', ''],
                [55, 9, 'California,United_States,North_America', 'United States', 'US', 'California', 'California'],
                [56, 9, 'Cambodia,Southeast_Asia,Asia', 'Cambodia', 'KH', '', ''],
                [57, 9, 'Canada,North_America', 'Canada', 'CA', '', ''],
                [58, 9, 'Cancun,Mexico,Western_Caribbean,Caribbean', 'Mexico', 'MX', 'Canc?n', ''],
                [59, 9, 'Cannes,France,Europe', 'France', 'FR', 'Cannes', ''],
                [60, 9, 'Cannon_Beach,Oregon,United_States,North_America', 'United States', 'US', 'Cannon Beach', ''],
                [61, 9, 'Cape_Town,South_Africa,Africa', 'South Africa', 'ZA', 'Cape Town', ''],
                [62, 9, 'Capri,Italy,Europe', 'Italy', 'IT', 'Capri', ''],
                [63, 9, 'Carmel,California,United_States,North_America', 'United States', 'US', 'Carmel', ''],
                [64, 9, 'Carnarvon,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Carnarvon', ''],
                [65, 9, 'Cebu,Philippines,Southeast_Asia,Asia', 'Philippines', 'PH', 'Cebu', 'Cebu'],
                [66, 9, 'Cervantes,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Cervantes', ''],
                [67, 9, 'Cheyenne,Wyoming,United_States,North_America', 'United States', 'US', 'Cheyenne', ''],
                [68, 9, 'Chiang_Mai,Thailand,Southeast_Asia,Asia', 'Thailand', 'TH', 'Chiang Mai', 'Chiang Mai'],
                [69, 9, 'Chiang_Rai,Thailand,Southeast_Asia,Asia', 'Thailand', 'TH', 'Chiang Rai', 'Chiang Rai'],
                [70, 9, 'Chicago,United_States,North_America', 'United States', 'US', 'Chicago', ''],
                [71, 9, 'China,Asia', 'China', 'CN', '', ''],
                [72, 9, 'Christchurch,South_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Christchurch', ''],
                [73, 9, 'Clinton,British_Columbia,Canada,North_America', 'Canada', 'CA', 'Clinton', ''],
                [74, 9, 'Cody,Wyoming,United_States,North_America', 'United States', 'US', 'Cody', ''],
                [75, 9, 'Coffs_Harbour,New_South_Wales,Australia,Australasia', 'Australia', 'AU', 'Coffs Harbour', ''],
                [76, 9, 'Colombo,Sri_Lanka,Southeast_Asia,Asia', 'Sri Lanka', 'LK', 'Colombo', ''],
                [77, 9, 'Colorado,United_States,North_America', 'United States', 'US', 'Colorado', 'Colorado'],
                [78, 9, 'Colorado_Springs,Colorado,United_States,North_America', 'United States', 'US', 'Colorado Springs', ''],
                [79, 9, 'Coral_Bay,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Coral Bay', ''],
                [80, 9, 'Cordoba,Spain,Europe', 'Spain', 'ES', 'C?rdoba', ''],
                [81, 9, 'Coromandel,North_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Coromandel', ''],
                [82, 9, 'Croatia,Europe', 'Croatia', 'HR', '', ''],
                [83, 9, 'Cuba,Eastern_Caribbean,Caribbean', 'Cuba', 'CU', 'Cuba', ''],
                [84, 9, 'Dallas,Texas,United_States,North_America', 'United States', 'US', 'Dallas', ''],
                [85, 9, 'Darwin,Northern_Territory,Australia,Australasia', 'Australia', 'AU', 'Darwin', ''],
                [86, 9, 'Dawson_City,Yukon,Canada,North_America', 'Canada', 'CA', 'Dawson City', ''],
                [87, 9, 'Daylesford,Victoria,Australia,Australasia', 'Australia', 'AU', 'Daylesford', ''],
                [88, 9, 'Deadwood,United_States,North_America', 'United States', 'US', 'Deadwood', ''],
                [89, 9, 'Delhi,India,Southeast_Asia,Asia', 'India', 'IN', 'Delhi', 'Delhi'],
                [90, 9, 'Denver,Colorado,United_States,North_America', 'United States', 'US', 'Denver', ''],
                [91, 9, 'Dubai,Middle_East,United_Arab_Emirates', 'United Arab Emirates', 'AE', 'Dubai', 'Dubai'],
                [92, 9, 'Dubrovnik,Croatia,Europe', 'Croatia', 'HR', 'Dubrovnik', ''],
                [93, 9, 'Duck_Key,Florida,United_States,North_America', 'United States', 'US', 'Duck Key', ''],
                [94, 9, 'Dunedin,South_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Dunedin', ''],
                [95, 9, 'Durango,Colorado,United_States,North_America', 'United States', 'US', 'Durango', ''],
                [96, 9, 'Durban,South_Africa,Africa', 'South Africa', 'ZA', 'Durban', ''],
                [97, 9, 'Edmonton,Alberta,Canada,North_America', 'Canada', 'CA', 'Edmonton', ''],
                [98, 9, 'Ella,Sri_Lanka,Southeast_Asia,Asia', 'Sri Lanka', 'LK', 'Ella', ''],
                [99, 9, 'El_Nido,Philippines,Southeast_Asia,Asia', 'Philippines', 'PH', 'El Nido', ''],
                [100, 9, 'Exmouth,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Exmouth', ''],
                [101, 9, 'Fairbanks,Alaska,United_States,North_America', 'United States', 'US', 'Fairbanks', ''],
                [102, 9, 'Fiji,South_Pacific', 'Fiji', 'FJ', '', ''],
                [103, 9, 'Florence,Italy,Europe', 'Italy', 'IT', 'Florence', ''],
                [104, 9, 'Florida,United_States,North_America', 'United States', 'US', 'Florida', 'Florida'],
                [105, 9, 'Fort_Collins,Colorado,United_States,North_America', 'United States', 'US', 'Fort Collins', ''],
                [106, 9, 'France,Europe', 'France', 'FR', 'France', ''],
                [107, 9, 'Franschhoek,Western_Cape,Garden_Route,South_Africa,Africa', 'South Africa', 'ZA', 'Franschhoek', ''],
                [108, 9, 'Franz_Josef,South_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Franz Josef', ''],
                [109, 9, 'Fremantle,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Fremantle', ''],
                [110, 9, 'Galle,Sri_Lanka,Southeast_Asia,Asia', 'Sri Lanka', 'LK', 'Galle', ''],
                [111, 9, 'Gander,Canada,North_America', 'Canada', 'CA', 'Gander', ''],
                [112, 9, 'Geraldton,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Geraldton', ''],
                [113, 9, 'Germany,Europe', 'Germany', 'DE', '', ''],
                [114, 9, 'Glenelg,Adelaide,South_Australia,Australia,Australasia', 'Australia', 'AU', 'Glenelg', ''],
                [115, 9, 'Gold_Bridge,British_Columbia,Canada,North_America', 'Canada', 'CA', 'Gold Bridge', ''],
                [116, 9, 'Gold_Coast,Queensland,Australia,Australasia', 'Australia', 'AU', 'Gold Coast', ''],
                [117, 9, 'Graham,Texas,United_States,North_America', 'United States', 'US', 'Graham', ''],
                [118, 9, 'Granada,Spain,Europe', 'Spain', 'ES', 'Granada', ''],
                [119, 9, 'Grand_Canyon,Arizona,United_States,North_America', 'United States', 'US', 'Grand Canyon', ''],
                [120, 9, 'Grand_Junction,Colorado,United_States,North_America', 'United States', 'US', 'Grand Junction', ''],
                [121, 9, 'Greece,Europe', 'Greece', 'GR', '', ''],
                [122, 9, 'Grenada,Southern_Caribbean,Caribbean', 'Grenada', 'GD', '', ''],
                [123, 9, 'Gwalior,India,Southeast_Asia,Asia', 'India', 'IN', 'Gwalior', ''],
                [124, 9, 'Haines_Junction,Yukon,Canada,North_America', 'Canada', 'CA', 'Haines Junction', ''],
                [125, 9, 'Hakone,Japan,Asia', 'Japan', 'JP', 'Hakone', ''],
                [126, 9, 'Hamilton_Island,Great_Barrier_Reef,Queensland,Australia,Australasia', 'Australia', 'AU', 'Hamilton Island', ''],
                [127, 9, 'Hanoi,Vietnam,Southeast_Asia,Asia', 'Vietnam', 'VN', 'Hanoi', ''],
                [128, 9, 'Havana,Cuba,Eastern_Caribbean,Caribbean', 'Cuba', 'CU', 'Havana', ''],
                [129, 9, 'Hawaii,United_States,North_America', 'United States', 'US', '', 'Hawaii'],
                [130, 9, 'Hermanus,South_Africa,Africa', 'South Africa', 'ZA', 'Hermanus', ''],
                [131, 9, 'Hervey_Bay,Queensland,Australia,Australasia', 'Australia', 'AU', 'Hervey Bay', ''],
                [132, 9, 'Hiroshima,Japan,Asia', 'Japan', 'JP', 'Hiroshima', 'Hiroshima'],
                [133, 9, 'Hobart,Tasmania,Australia,Australasia', 'Australia', 'AU', 'Hobart', ''],
                [134, 9, 'Ho_Chi_Minh_City,Vietnam,Southeast_Asia,Asia', 'Vietnam', 'VN', 'Ho Chi Minh City', ''],
                [135, 9, 'Hoi_An,Vietnam,Southeast_Asia,Asia', 'Vietnam', 'VN', 'Hoi An', ''],
                [136, 9, 'Holbrook,United_States,North_America', 'United States', 'US', 'Holbrook', ''],
                [137, 9, 'Honolulu,Hawaii,United_States,North_America', 'United States', 'US', 'Honolulu', ''],
                [138, 9, 'Hua_Hin,Thailand,Southeast_Asia,Asia', 'Thailand', 'TH', 'Hua Hin', ''],
                [139, 9, 'Hue,Vietnam,Southeast_Asia,Asia', 'Vietnam', 'VN', 'Hue', ''],
                [140, 9, 'Hungary,Europe', 'Hungary', 'HU', '', ''],
                [141, 9, 'Huntsville,Ontario,Canada,North_America', 'Canada', 'CA', 'Huntsville', ''],
                [142, 9, 'Iceland,Europe', 'Iceland', 'IS', '', ''],
                [143, 9, 'India,Southeast_Asia,Asia', 'India', 'IN', '', ''],
                [144, 9, 'Indonesia,Southeast_Asia,Asia', 'Indonesia', 'ID', '', ''],
                [145, 9, 'Islamorada,Florida,United_States,North_America', 'United States', 'US', 'Islamorada', ''],
                [146, 9, 'Italy,Europe', 'Italy', 'IT', '', ''],
                [147, 9, 'Jackson,Maine,United_States,North_America', 'United States', 'US', 'Jackson', ''],
                [148, 9, 'Jaipur,India,Southeast_Asia,Asia', 'India', 'IN', 'Jaipur', ''],
                [149, 9, 'Jamaica,Eastern_Caribbean,Caribbean', 'Jamaica', 'JM', '', ''],
                [150, 9, 'Japan,Asia', 'Japan', 'JP', '', ''],
                [151, 9, 'Jasper,Alberta,Canada,North_America', 'Canada', 'CA', 'Jasper', ''],
                [152, 9, 'Jervis_Bay,New_South_Wales,Australia,Australasia', 'Australia', 'AU', 'Jervis Bay', ''],
                [153, 9, 'Johannesburg,South_Africa,Africa', 'South Africa', 'ZA', 'Johannesburg', ''],
                [154, 9, 'Kaikoura,South_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Kaikoura', ''],
                [155, 9, 'Kalbarri,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Kalbarri', ''],
                [156, 9, 'Kamloops,British_Columbia,Canada,North_America', 'Canada', 'CA', 'Kamloops', ''],
                [157, 9, 'Kanazawa,Japan,Asia', 'Japan', 'JP', 'Kanazawa', ''],
                [158, 9, 'Kanchanaburi,Thailand,Southeast_Asia,Asia', 'Thailand', 'TH', 'Kanchanaburi', 'Kanchanaburi'],
                [159, 9, 'Kandy,Sri_Lanka,Southeast_Asia,Asia', 'Sri Lanka', 'LK', 'Kandy', ''],
                [160, 9, 'Katherine,Northern_Territory,Australia,Australasia', 'Australia', 'AU', 'Katherine', ''],
                [161, 9, 'Kelowna,British_Columbia,Canada,North_America', 'Canada', 'CA', 'Kelowna', ''],
                [162, 9, 'Kennebunkport,Maine,United_States,North_America', 'United States', 'US', 'Kennebunkport', ''],
                [163, 9, 'Kenya,East_Africa,Africa', 'Kenya', 'KE', '', ''],
                [164, 9, 'Key_West,Florida,United_States,North_America', 'United States', 'US', 'Key West', ''],
                [165, 9, 'Khajuraho,India,Southeast_Asia,Asia', 'India', 'IN', 'Khajuraho', ''],
                [166, 9, 'Kiama,New_South_Wales,Australia,Australasia', 'Australia', 'AU', 'Kiama', ''],
                [167, 9, 'Kingston,Ontario,Canada,North_America', 'Canada', 'CA', 'Kingston', ''],
                [168, 9, 'Klemtu,British_Columbia,Canada,North_America', 'Canada', 'CA', 'Klemtu', ''],
                [169, 9, 'Knysna,South_Africa,Africa', 'South Africa', 'ZA', 'Knysna', ''],
                [170, 9, 'Kochi,India,Southeast_Asia,Asia', 'India', 'IN', 'Kochi', ''],
                [171, 9, 'Kor?ula,Croatia,Europe', 'Croatia', 'HR', 'Korcula', ''],
                [172, 9, 'Kota_Kinabalu,Borneo,Malaysia,Southeast_Asia,Asia', 'Malaysia', 'MY', 'Kota Kinabalu', ''],
                [173, 9, 'Kovalam,India,Southeast_Asia,Asia', 'India', 'IN', 'Kovalam', ''],
                [174, 9, 'Koyasan,Japan,Asia', 'Japan', 'JP', 'Koyasan', ''],
                [175, 9, 'Krabi,Thailand,Southeast_Asia,Asia', 'Thailand', 'TH', 'Krabi', 'Krabi'],
                [176, 9, 'Kuala_Lumpur,Malaysia,Southeast_Asia,Asia', 'Malaysia', 'MY', 'Kuala Lumpur', 'Kuala Lumpur'],
                [177, 9, 'Kuching,Malaysia,Southeast_Asia,Asia', 'Malaysia', 'MY', 'Kuching', ''],
                [178, 9, 'Kyoto,Japan,Asia', 'Japan', 'JP', '', 'Kyoto'],
                [179, 9, 'Ladysmith,South_Africa,Africa', 'South Africa', 'ZA', 'Ladysmith', ''],
                [180, 9, 'Lake_Louise,Alberta,Canada,North_America', 'Canada', 'CA', 'Lake Louise', ''],
                [181, 9, 'Lakes_Entrance,Victoria,Australia,Australasia', 'Australia', 'AU', 'Lakes Entrance', ''],
                [182, 9, 'Lake_Tekapo,South_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Lake Tekapo', ''],
                [183, 9, 'La_Malbaie,Quebec,Canada,North_America', 'Canada', 'CA', 'La Malbaie', ''],
                [184, 9, 'Lander,Wyoming,United_States,North_America', 'United States', 'US', 'Lander', ''],
                [185, 9, 'Langkawi,Malaysia,Southeast_Asia,Asia', 'Malaysia', 'MY', 'Langkawi', ''],
                [186, 9, 'Laramie,Wyoming,United_States,North_America', 'United States', 'US', 'Laramie', ''],
                [187, 9, 'La_Rioja,Spain,Europe', 'Spain', 'ES', '', 'La Rioja'],
                [188, 9, 'Las_Vegas,Nevada,United_States,North_America', 'United States', 'US', 'Las Vegas', ''],
                [189, 9, 'Launceston,Tasmania,Australia,Australasia', 'Australia', 'AU', 'Launceston', ''],
                [190, 9, 'Lenox,Massachusetts,United_States,North_America', 'United States', 'US', 'Lenox', ''],
                [191, 9, 'Lisbon,Portugal,Europe', 'Portugal', 'PT', 'Lisbon', ''],
                [192, 9, 'Lorne,Great_Ocean_Road,Victoria,Australia,Australasia', 'Australia', 'AU', 'Lorne', ''],
                [193, 9, 'Los_Angeles,California,United_States,North_America', 'United States', 'US', 'Los Angeles', ''],
                [194, 9, 'Louisiana,United_States,North_America', 'United States', 'US', 'Louisiana', 'Louisiana'],
                [195, 9, 'Louisville,United_States,North_America', 'United States', 'US', 'Louisville', ''],
                [196, 9, 'Madrid,Spain,Europe', 'Spain', 'ES', 'Madrid', 'Madrid'],
                [197, 9, 'Mae_Hong_Son,Thailand,Southeast_Asia,Asia', 'Thailand', 'TH', 'Mae Hong Son', 'Mae Hong Son'],
                [198, 9, 'Maine,United_States,North_America', 'United States', 'US', 'Maine', 'Maine'],
                [199, 9, 'Malacca,Malaysia,Southeast_Asia,Asia', 'Malaysia', 'MY', 'Malacca', ''],
                [200, 9, 'Malaysia,Southeast_Asia,Asia', 'Malaysia', 'MY', '', ''],
                [201, 9, 'Maleny,Queensland,Australia,Australasia', 'Australia', 'AU', 'Maleny', ''],
                [202, 9, 'Malta,Europe', 'Malta', 'MT', '', ''],
                [203, 9, 'Manila,Philippines,Southeast_Asia,Asia', 'Philippines', 'PH', 'Manila', 'Manila'],
                [204, 9, 'Marbella,Spain,Europe', 'Spain', 'ES', 'Marbella', ''],
                [205, 9, 'Margaret_River,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Margaret River', ''],
                [206, 9, 'Marlborough,South_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', '', 'Marlborough'],
                [207, 9, 'Maryvale,Queensland,Australia,Australasia', 'Australia', 'AU', 'Maryvale', ''],
                [208, 9, 'Massachusetts,United_States,North_America', 'United States', 'US', '', 'Massachusetts'],
                [209, 9, 'Matsumoto,Japan,Asia', 'Japan', 'JP', 'Matsumoto', ''],
                [210, 9, 'Melbourne,Victoria,Australia,Australasia', 'Australia', 'AU', 'Melbourne', ''],
                [211, 9, 'Memphis,Tennessee,United_States,North_America', 'United States', 'US', 'Memphis', ''],
                [212, 9, 'Merimbula,New_South_Wales,Australia,Australasia', 'Australia', 'AU', 'Merimbula', ''],
                [213, 9, 'Mexico,Western_Caribbean,Caribbean', 'Mexico', 'MX', 'M?xico', 'Mexico'],
                [214, 9, 'Miami,Florida,United_States,North_America', 'United States', 'US', 'Miami', ''],
                [215, 9, 'Milan,Italy,Europe', 'Italy', 'IT', 'Milan', ''],
                [216, 9, 'Mission_Beach,Queensland,Australia,Australasia', 'Australia', 'AU', 'Mission Beach', ''],
                [217, 9, 'Mississippi,United_States,North_America', 'United States', 'US', '', 'Mississippi'],
                [218, 9, 'Mkuze,South_Africa,Africa', 'South Africa', 'ZA', 'Mkuze', ''],
                [219, 9, 'Moab,Utah,United_States,North_America', 'United States', 'US', 'Moab', ''],
                [220, 9, 'Mobile,Alabama,United_States,North_America', 'United States', 'US', 'Mobile', ''],
                [221, 9, 'Monkey_Mia,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Monkey Mia', ''],
                [222, 9, 'Monterey,California,United_States,North_America', 'United States', 'US', 'Monterey', ''],
                [223, 9, 'Montgomery,Alabama,United_States,North_America', 'United States', 'US', 'Montgomery', ''],
                [224, 9, 'Montreal,Quebec,Canada,North_America', 'Canada', 'CA', 'Montreal', ''],
                [225, 9, 'Mount_Hood,Oregon,United_States,North_America', 'United States', 'US', 'Mount Hood', ''],
                [226, 9, 'Munnar,India,Southeast_Asia,Asia', 'India', 'IN', 'Munnar', ''],
                [227, 9, 'Mykonos,Greece,Europe', 'Greece', 'GR', 'M?konos', ''],
                [228, 9, 'Nagano,Japan,Asia', 'Japan', 'JP', 'Nagano', 'Nagano'],
                [229, 9, 'Nairobi,Kenya,East_Africa,Africa', 'Kenya', 'KE', 'Nairobi', ''],
                [230, 9, 'Napier,North_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Napier', ''],
                [231, 9, 'Naples,Italy,Europe', 'Italy', 'IT', 'Naples', ''],
                [232, 9, 'Nashville,Tennessee,United_States,North_America', 'United States', 'US', 'Nashville', ''],
                [233, 9, 'Natchez,Mississippi,United_States,North_America', 'United States', 'US', 'Natchez', ''],
                [234, 9, 'Negombo,Sri_Lanka,Southeast_Asia,Asia', 'Sri Lanka', 'LK', 'Negombo', ''],
                [235, 9, 'Nelson,South_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Nelson', 'Nelson'],
                [236, 9, 'Netherlands,Europe', 'Netherlands', 'NL', '', ''],
                [237, 9, 'Nevada,United_States,North_America', 'United States', 'US', 'Nevada', 'Nevada'],
                [238, 9, 'New_Orleans,Louisiana,United_States,North_America', 'United States', 'US', 'New Orleans', ''],
                [239, 9, 'Newport,Rhode_Island,United_States,North_America', 'United States', 'US', 'Newport', ''],
                [240, 9, 'Newport_Beach,California,United_States,North_America', 'United States', 'US', 'Newport Beach', ''],
                [241, 9, 'New_South_Wales,Australia,Australasia', 'Australia', 'AU', '', 'New South Wales'],
                [242, 9, 'New_York,United_States,North_America', 'United States', 'US', 'New York', 'New York'],
                [243, 9, 'New_Zealand,Australasia', 'New Zealand', 'NZ', '', ''],
                [244, 9, 'Nha_Trang,Vietnam,Southeast_Asia,Asia', 'Vietnam', 'VN', 'Nha Trang', ''],
                [245, 9, 'Niagara_Falls,Canada,North_America', 'Canada', 'CA', 'Niagara Falls', ''],
                [246, 9, 'Nice,France,Europe', 'France', 'FR', 'Nice', ''],
                [247, 9, 'Ninh_Binh,Vietnam,Southeast_Asia,Asia', 'Vietnam', 'VN', 'Ninh B?nh', 'Ninh Binh'],
                [248, 9, 'Noosa,Queensland,Australia,Australasia', 'Australia', 'AU', 'Noosa', ''],
                [249, 9, 'Northern_Territory,Australia,Australasia', 'Australia', 'AU', 'Northern Territory', 'Northern Territory'],
                [250, 9, 'Nusa_Dua,Bali,Indonesia,Southeast_Asia,Asia', 'Indonesia', 'ID', 'Nusa Dua', ''],
                [251, 9, 'Nuwara_Eliya,Sri_Lanka,Southeast_Asia,Asia', 'Sri Lanka', 'LK', 'Nuwara Eliya', ''],
                [252, 9, 'Ontario,Canada,North_America', 'Canada', 'CA', '', 'Ontario'],
                [253, 9, 'Oregon,United_States,North_America', 'United States', 'US', 'Oregon', 'Oregon'],
                [254, 9, 'Orlando,Florida,United_States,North_America', 'United States', 'US', 'Orlando', ''],
                [255, 9, 'Osaka,Japan,Asia', 'Japan', 'JP', 'Osaka', 'Osaka'],
                [256, 9, 'Osoyoos,British_Columbia,Canada,North_America', 'Canada', 'CA', 'Osoyoos', ''],
                [257, 9, 'Ottawa,Ontario,Canada,North_America', 'Canada', 'CA', 'Ottawa', ''],
                [258, 9, 'Oudtshoorn,South_Africa,Africa', 'South Africa', 'ZA', 'Oudtshoorn', ''],
                [259, 9, 'Palm_Springs,California,United_States,North_America', 'United States', 'US', 'Palm Springs', ''],
                [260, 9, 'Paragpur,India,Southeast_Asia,Asia', 'India', 'IN', 'Paragpur', ''],
                [261, 9, 'Paris,France,Europe', 'France', 'FR', 'Paris', ''],
                [262, 9, 'Paros,Greece,Europe', 'Greece', 'GR', 'P?ros', ''],
                [263, 9, 'Pemberton,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Pemberton', ''],
                [264, 9, 'Pembroke,Ontario,Canada,North_America', 'Canada', 'CA', 'Pembroke', ''],
                [265, 9, 'Penang,Malaysia,Southeast_Asia,Asia', 'Malaysia', 'MY', 'Penang', ''],
                [266, 9, 'Penticton,British_Columbia,Canada,North_America', 'Canada', 'CA', 'Penticton', ''],
                [267, 9, 'Perth,Western_Australia,Australia,Australasia', 'Australia', 'AU', 'Perth', ''],
                [268, 9, 'Philippines,Southeast_Asia,Asia', 'Philippines', 'PH', '', ''],
                [269, 9, 'Phnom_Penh,Cambodia,Southeast_Asia,Asia', 'Cambodia', 'KH', 'Phnom Penh', ''],
                [270, 9, 'Phoenix,Arizona,United_States,North_America', 'United States', 'US', 'Phoenix', ''],
                [271, 9, 'Phuket,Thailand,Southeast_Asia,Asia', 'Thailand', 'TH', 'Phuket', 'Phuket'],
                [272, 9, 'Pienza,Italy,Europe', 'Italy', 'IT', 'Pienza', ''],
                [273, 9, 'Pietermaritzburg,South_Africa,Africa', 'South Africa', 'ZA', 'Pietermaritzburg', ''],
                [274, 9, 'Pilanesberg,South_Africa,Africa', 'South Africa', 'ZA', 'Pilanesberg', ''],
                [275, 9, 'Pisa,Italy,Europe', 'Italy', 'IT', 'Pisa', ''],
                [276, 9, 'Pismo_Beach,California,United_States,North_America', 'United States', 'US', 'Pismo Beach', ''],
                [277, 9, 'Plettenberg_Bay,Western_Cape,Garden_Route,South_Africa,Africa', 'South Africa', 'ZA', 'Plettenberg Bay', ''],
                [278, 9, 'Port_Arthur,Tasmania,Australia,Australasia', 'Australia', 'AU', 'Port Arthur', ''],
                [279, 9, 'Port_Douglas,Queensland,Australia,Australasia', 'Australia', 'AU', 'Port Douglas', ''],
                [280, 9, 'Portland,Oregon,United_States,North_America', 'United States', 'US', 'Portland', ''],
                [281, 9, 'Porto,Portugal,Europe', 'Portugal', 'PT', 'Porto', 'Porto'],
                [282, 9, 'Portugal,Europe', 'Portugal', 'PT', 'Portugal', ''],
                [283, 9, 'Positano,Italy,Europe', 'Italy', 'IT', 'Positano', ''],
                [284, 9, 'Pretoria,South_Africa,Africa', 'South Africa', 'ZA', 'Pretoria', ''],
                [285, 9, 'Quebec,Canada,North_America', 'Canada', 'CA', 'Quebec', 'Quebec'],
                [286, 9, 'Queensland,Australia,Australasia', 'Australia', 'AU', '', 'Queensland'],
                [287, 9, 'Queenstown,South_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Queenstown', ''],
                [288, 9, 'Reykjavik,Iceland,Europe', 'Iceland', 'IS', 'Reykjav?k', ''],
                [289, 9, 'Rhode_Island,United_States,North_America', 'United States', 'US', 'Rhode Island', 'Rhode Island'],
                [290, 9, 'Robe,Great_Ocean_Road,Victoria,Australia,Australasia', 'Australia', 'AU', 'Robe', ''],
                [291, 9, 'Rome,Italy,Europe', 'Italy', 'IT', 'Rome', ''],
                [292, 9, 'Ronda,Spain,Europe', 'Spain', 'ES', 'Ronda', ''],
                [293, 9, 'Saint_Lucia,Southern_Caribbean,Caribbean', 'Saint Lucia', 'LC', '', ''],
                [294, 9, 'Sandakan,Borneo,Malaysia,Southeast_Asia,Asia', 'Malaysia', 'MY', 'Sandakan', ''],
                [295, 9, 'San_Diego,California,United_States,North_America', 'United States', 'US', 'San Diego', ''],
                [296, 9, 'San_Francisco,California,United_States,North_America', 'United States', 'US', 'San Francisco', ''],
                [297, 9, 'San_Gimignano_,Italy,Europe', 'Italy', 'IT', 'San Gimignano', ''],
                [298, 9, 'San_Sebastian,Spain,Europe', 'Spain', 'ES', 'San Sebastian', ''],
                [299, 9, 'San_Simeon,California,United_States,North_America', 'United States', 'US', 'San Simeon', ''],
                [300, 9, 'Santa_Barbara,California,United_States,North_America', 'United States', 'US', 'Santa Barbara', ''],
                [301, 9, 'Santa_Rosa,California,United_States,North_America', 'United States', 'US', 'Santa Rosa', ''],
                [302, 9, 'Sa_Pa,Vietnam,Southeast_Asia,Asia', 'Vietnam', 'VN', 'Sa Pa', ''],
                [303, 9, 'Sarlat,France,Europe', 'France', 'FR', 'Sarlat', ''],
                [304, 9, 'Seattle,Washington__,United_States,North_America', 'United States', 'US', 'Seattle', ''],
                [305, 9, 'Seminyak,Bali,Indonesia,Southeast_Asia,Asia', 'Indonesia', 'ID', 'Seminyak', ''],
                [306, 9, 'Senggigi,Indonesia,Southeast_Asia,Asia', 'Indonesia', 'ID', 'Senggigi', ''],
                [307, 9, 'Sepilok,Malaysia,Southeast_Asia,Asia', 'Malaysia', 'MY', 'Sepilok', ''],
                [308, 9, 'Sequoia_National_Park,California,United_States,North_America', 'United States', 'US', 'Sequoia National Park', ''],
                [309, 9, 'Seville,Spain,Europe', 'Spain', 'ES', 'Seville', ''],
                [310, 9, 'Seward,Alaska,United_States,North_America', 'United States', 'US', 'Seward', ''],
                [311, 9, 'Shanghai,China,Asia', 'China', 'CN', 'Shanghai', 'Shanghai'],
                [312, 9, 'Shimla,India,Southeast_Asia,Asia', 'India', 'IN', 'Shimla', ''],
                [313, 9, 'Siem_Reap,Cambodia,Southeast_Asia,Asia', 'Cambodia', 'KH', 'Siem Reap', 'Siem Reap'],
                [314, 9, 'Sigiriya,Sri_Lanka,Southeast_Asia,Asia', 'Sri Lanka', 'LK', 'Sigiriya', ''],
                [315, 9, 'Singapore,Southeast_Asia,Asia', 'Singapore', 'SG', 'Singapore', ''],
                [316, 9, 'Sisters,Oregon,United_States,North_America', 'United States', 'US', 'Sisters', ''],
                [317, 9, 'Sorrento,Naples,Italy,Europe', 'Italy', 'IT', 'Sorrento', ''],
                [318, 9, 'South_Africa,Africa', 'South Africa', 'ZA', '', ''],
                [319, 9, 'South_Australia,Australia,Australasia', 'Australia', 'AU', '', 'South Australia'],
                [320, 9, 'Spain,Europe', 'Spain', 'ES', '', ''],
                [321, 9, 'Split,Croatia,Europe', 'Croatia', 'HR', 'Split', ''],
                [322, 9, 'Springfield,United_States,North_America', 'United States', 'US', 'Springfield', ''],
                [323, 9, 'Sri_Lanka,Southeast_Asia,Asia', 'Sri Lanka', 'LK', '', ''],
                [324, 9, 'Stellenbosch,Western_Cape,Garden_Route,South_Africa,Africa', 'South Africa', 'ZA', 'Stellenbosch', ''],
                [325, 9, 'Strahan,Tasmania,Australia,Australasia', 'Australia', 'AU', 'Strahan', ''],
                [326, 9, 'Sunriver,Oregon,United_States,North_America', 'United States', 'US', 'Sunriver', ''],
                [327, 9, 'Surakarta,Indonesia,Southeast_Asia,Asia', 'Indonesia', 'ID', 'Surakarta', ''],
                [328, 9, 'Sydney,New_South_Wales,Australia,Australasia', 'Australia', 'AU', 'Sydney', ''],
                [329, 9, 'Syracuse,Italy,Europe', 'Italy', 'IT', 'Syracuse', ''],
                [330, 9, 'Tak,Thailand,Southeast_Asia,Asia', 'Thailand', 'TH', 'Tak', 'Tak'],
                [331, 9, 'Takayama,Japan,Asia', 'Japan', 'JP', 'Takayama', ''],
                [332, 9, 'Tanzania,East_Africa,Africa', 'Tanzania', 'TZ', '', ''],
                [333, 9, 'Tasmania,Australia,Australasia', 'Australia', 'AU', '', 'Tasmania'],
                [334, 9, 'Taupo,North_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Taupo', ''],
                [335, 9, 'Te_Anau,South_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Te Anau', ''],
                [336, 9, 'Tennessee,United_States,North_America', 'United States', 'US', 'Tennessee', 'Tennessee'],
                [337, 9, 'Texas,United_States,North_America', 'United States', 'US', 'Texas', 'Texas'],
                [338, 9, 'Thailand,Southeast_Asia,Asia', 'Thailand', 'TH', '', ''],
                [339, 9, 'Tillamook,Oregon,United_States,North_America', 'United States', 'US', 'Tillamook', ''],
                [340, 9, 'Tofino,British_Columbia,Canada,North_America', 'Canada', 'CA', 'Tofino', ''],
                [341, 9, 'Tokyo,Japan,Asia', 'Japan', 'JP', 'Tokyo', 'Tokyo'],
                [342, 9, 'Toledo,Spain,Europe', 'Spain', 'ES', 'Toledo', ''],
                [343, 9, 'Toronto,Ontario,Canada,North_America', 'Canada', 'CA', 'Toronto', ''],
                [344, 9, 'Trincomalee,Sri_Lanka,Southeast_Asia,Asia', 'Sri Lanka', 'LK', 'Trincomalee', ''],
                [345, 9, 'Tucson,Arizona,United_States,North_America', 'United States', 'US', 'Tucson', ''],
                [346, 9, 'Twillingate,Canada,North_America', 'Canada', 'CA', 'Twillingate', ''],
                [347, 9, 'Ubud,Bali,Indonesia,Southeast_Asia,Asia', 'Indonesia', 'ID', 'Ubud', ''],
                [348, 9, 'United_Arab_Emirates', 'United Arab Emirates', 'AE', '', ''],
                [349, 9, 'United_States,North_America', 'United States', 'US', '', ''],
                [350, 9, 'Utah,United_States,North_America', 'United States', 'US', 'Utah', 'Utah'],
                [351, 9, 'Valdez,Alaska,United_States,North_America', 'United States', 'US', 'Valdez', ''],
                [352, 9, 'Vancouver,British_Columbia,Canada,North_America', 'Canada', 'CA', 'Vancouver', ''],
                [353, 9, 'Varadero,Cuba,Eastern_Caribbean,Caribbean', 'Cuba', 'CU', 'Varadero', ''],
                [354, 9, 'Varanasi,India,Southeast_Asia,Asia', 'India', 'IN', 'Varanasi', ''],
                [355, 9, 'Venice,Italy,Europe', 'Italy', 'IT', 'Venice', ''],
                [356, 9, 'Vermont,United_States,North_America', 'United States', 'US', 'Vermont', 'Vermont'],
                [357, 9, 'Verona,Italy,Europe', 'Italy', 'IT', 'Verona', ''],
                [358, 9, 'Vicksburg,United_States,North_America', 'United States', 'US', 'Vicksburg', ''],
                [359, 9, 'Victoria,Australia,Australasia', 'Australia', 'AU', '', 'Victoria'],
                [360, 9, 'Victoria,British_Columbia,Canada,North_America', 'Canada', 'CA', 'Victoria', ''],
                [361, 9, 'Vienna,Austria,Europe', 'Austria', 'AT', 'Vienna', ''],
                [362, 9, 'Vietnam,Southeast_Asia,Asia', 'Vietnam', 'VN', '', ''],
                [363, 9, 'Vinales,Cuba,Eastern_Caribbean,Caribbean', 'Cuba', 'CU', 'Vi?ales', ''],
                [364, 9, 'Wanaka,South_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Wanaka', ''],
                [365, 9, 'Warrnambool,Great_Ocean_Road,Victoria,Australia,Australasia', 'Australia', 'AU', 'Warrnambool', ''],
                [366, 9, 'Washington__,United_States,North_America', 'United States', 'US', 'Washington', 'Washington'],
                [367, 9, 'Watson_Lake,Yukon,Canada,North_America', 'Canada', 'CA', 'Watson Lake', ''],
                [368, 9, 'Wellington,North_Island,New_Zealand,Australasia', 'New Zealand', 'NZ', 'Wellington', 'Wellington'],
                [369, 9, 'Western_Australia,Australia,Australasia', 'Australia', 'AU', '', 'Western Australia'],
                [370, 9, 'Western_Cape,Garden_Route,South_Africa,Africa', 'South Africa', 'ZA', '', 'Western Cape'],
                [371, 9, 'White_Castle,Louisiana,United_States,North_America', 'United States', 'US', 'White Castle', ''],
                [372, 9, 'Whitehorse,Yukon,Canada,North_America', 'Canada', 'CA', 'Whitehorse', ''],
                [373, 9, 'Wyoming,United_States,North_America', 'United States', 'US', 'Wyoming', 'Wyoming'],
                [374, 9, 'Yangshuo,China,Asia', 'China', 'CN', 'Yangshuo', ''],
                [375, 9, 'Yogyakarta,Indonesia,Southeast_Asia,Asia', 'Indonesia', 'ID', 'Yogyakarta', 'Yogyakarta'],
                [376, 9, 'Yosemite,California,United_States,North_America', 'United States', 'US', 'Yosemite', ''],
                [377, 9, 'Zambia,Africa', 'Zambia', 'ZM', '', ''],
                [378, 9, 'Zanzibar,Tanzania,East_Africa,Africa', 'Tanzania', 'TZ', 'Zanzibar', ''],
            ]
        );

    }

    public function safeDown()
    {
        echo "m190627_120647_add_flightcentre cannot be reverted.\n";

        return false;
    }
}
